//meal actions
export const GET_MEALS = "GET_MEALS";
export const CREATE_MEAL = "CREATE_MEAL";
export const GET_MEAL_BY_ID = "GET_MEAL_BY_ID";
export const DELETE_MEAL = "DELETE_MEAL";

//meal plan action types
export const GET_MEALPLANS = "GET_MEALPLANS";
export const GET_MEALPLAN_BY_ID = "GET_MEALPLAN_BY_ID";
export const CREATE_MEALPLAN = "CREATE_MEALPLAN";
export const ADD_MEAL_TO_MEALPLAN = "ADD_MEAL_TO_MEALPLAN";
export const DELETE_MEAL_FROM_MEALPLAN = "DELETE_MEAL_FROM_MEALPLAN";
export const DELETE_MEALPLAN = "DELETE_MEALPLAN";

//grocery list action types

export const CREATE_GROCERY_LIST = "CREATE_GROCERY_LIST";
export const GET_GROCERY_LIST = "GET_GROCERY_LIST";

// week plan action types
export const GET_WEEKPLANS = "GET_WEEKPLANS";
export const GET_WEEKPLAN_BY_ID = "GET_WEEKPLAN_BY_ID";
export const CREATE_WEEKPLAN = "CREATE_WEEKPLAN";
export const ADD_MEALPLAN_TO_WEEKPLAN = "ADD_MEALPLAN_TO_WEEKPLAN";
export const DELETE_MEALPLAN_FROM_WEEKPLAN = "DELETE_MEALPLAN_FROM_WEEKPLAN";
export const DELETE_WEEKPLAN = "DELETE_WEEKPLAN";

// weekly grocery list action types

export const CREATE_WEEKLY_GROCERY_LIST = "CREATE_WEEKLY_GROCERY_LIST";
export const GET_WEEKLY_GROCERY_LIST = "GET_WEEKLY_GROCERY_LIST";
